# All server fields such as server | location can be set, such as:
# location /web {
#     try_files $uri $uri/ /index.php$is_args$args;
# }
# error_page 404 /diy_404.html;
# If there is abnormal access to the reverse proxy website and the content has already been configured here, please prioritize checking if the configuration here is correct

proxy_hide_header Content-Security-Policy;

add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdn.datatables.net https://cdnjs.cloudflare.com https://*.ys7.com https://*.ezvizlife.com blob:; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://fonts.bunny.net https://cdn.datatables.net https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://fonts.bunny.net https://cdn.jsdelivr.net data:; img-src 'self' data: blob: https://*.ezvizlife.com https://*.ys7.com; connect-src 'self' https://*.ezvizlife.com:* wss://*.ezvizlife.com:* https://*.ys7.com:* wss://*.ys7.com:* https://cdn.jsdelivr.net data: blob:; frame-src 'self' https://*.ezvizlife.com https://*.ys7.com blob:; worker-src 'self' blob: data:; child-src 'self' blob:; media-src 'self' blob: https://*.ezvizlife.com https://*.ys7.com;" always;
